 # ██████╗░██╗░██████╗░██╗░░░░░░░██╗░█████╗░░░░░░██╗██╗████████╗
 # ██╔══██╗██║██╔════╝░██║░░██╗░░██║██╔══██╗░░░░░██║██║╚══██╔══╝
 # ██████╦╝██║╚█████╗░░╚██╗████╗██╔╝███████║░░░░░██║██║░░░██║░░░
 # ██╔══██╗██║░╚═══██╗░░████╔═████║░██╔══██║██╗░░██║██║░░░██║░░░
 # ██████╦╝██║██████╔╝░░╚██╔╝░╚██╔╝░██║░░██║╚█████╔╝██║░░░██║░░░
 # ╚═════╝░╚═╝╚═════╝░░░░╚═╝░░░╚═╝░░╚═╝░░╚═╝░╚════╝░╚═╝░░░╚═╝░░░

# License: This configuration file is released under public domain.
# You are free to use, modify, and distribute this configuration as you wish.
# No attribution required.

database:
  # The database type. "sqlite" and "mysql" are supported.
  type: sqlite

  # Edit these settings only if you choose "sqlite".
  sqlite:
    # The file name of the database in the plugin data folder.
    # You can also put an absolute path here.
    file: skyblock.sql

  # Edit these settings only if you choose "mysql".
  mysql:
    host: 127.0.0.1
    # Avoid using the "root" user for security reasons.
    username: root
    password: ""
    schema: skyblock
  # The maximum number of simultaneous SQL queries
  # Recommended: 1 for sqlite, 2 for MySQL. You may want to further increase this value if your MySQL connection is very slow.
  worker-limit: 1

HUB: Hub

PREFIX: "§l§6SKYBLOCK§r §l§a»§r " 
SERVER-MOTD: §eYour Motd

# This sends all crash reports and startup logs to PixelForgeStudio!
# This does not create any security issues — it is only used to improve the plugin.
LOG-TO-PIXELFORGESTUDO: true

SERVER-NAME: §eYour Server
VOTE-WEBSITE: §ehttps:://yourvotelink.com
DISCORD-LINK: §ehttps:://discord.gg/yourdiscord

RESPAWN-TIME: 20 # block regain time in seconds farm, mine, forest...

PLAYER-COUNT: 1 # increace server max player count...

SERVER-IP: play.yourserver.com

SCOREBOARD-TITLE: "§9S§bky§3Block"
SCOREBOARD-TITLES:
  "§9S§bky§3Block": "§bS§9k§by§3Block"
  "§bS§9k§by§3Block": "§bSk§9y§3Block"
  "§bSk§9y§3Block": "§bSky§9B§3lock"
  "§bSky§9B§3lock": "§bSky§3B§9l§3ock"
  "§bSky§3B§9l§3ock": "§bSky§3Bl§9o§3ck"
  "§bSky§3Bl§9o§3ck": "§bSky§3Blo§9c§3k"
  "§bSky§3Blo§9c§3k": "§bSky§3Bloc§9k"
  "§bSky§3Bloc§9k": "§9S§bky§3Block"
